name: Node CI

on: [push]

jobs:
  #   build:

  #     runs-on: ubuntu-latest

  #     strategy:
  #       matrix:
  #         node-version: [11.x]

  #     steps:
  #     - uses: actions/checkout@v1
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: npm install, build and test
  #       run: |
  #         npm ci
  #         npm run build --if-present
  #         npm test
  #       env:
  #         CI: true
  deploy:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    strategy:
      matrix:
        node-version: [11.x]

    steps:
      - uses: actions/checkout@v1
      - name: Config git name / email
        run: |
          git init
          git config user.email "2480661+fernandreu@users.noreply.github.com"
          git config user.name "fernandreu"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and deploy
        run: |
          npm ci
          npm run deploy-ci --if-present
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
